export const SERVICES = {
  APPOINTMENT_CREATED_CLIENT: 'APPOINTMENT_CREATED_CLIENT',
  APPOINTMENT_UPDATED_CLIENT: 'APPOINTMENT_UPDATED_CLIENT',
  APPOINTMENT_DELETED_CLIENT: 'APPOINTMENT_DELETED_CLIENT',
};
