name: CI - Scheduling Microservice

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧹 Rodar lint
        run: npm run lint

      - name: 🧪 Rodar testes
        run: npm run test

      - name: Build API Gateway
        run: npx nest build api-gateway

      - name: Build Auth
        run: npx nest build auth-service

      - name: Build Scheduling
        run: npx nest build scheduling-service

      - name: Build Notification
        run: npx nest build notification-service
